### ISSUE TITLE
Missing script on CharacterController GameObject (child of the Player GameObject)

### ISSUE THREAD

**Issue by AlexanderGheorghe** [dejaime/thats-ridiculous#1]
There's a missing script on the CharacterController GameObject in the Game scene. The PlayerMovement and CameraMouseInput are there, but there is a third script that is missing. I think this causes the player to fire continuously and makes the charging of the weapon not work.

**Comment by dejaime** [comment]
Oh, hi, thank you for the issue, and sorry for the huge delay on the response! I missed the notification, it seems.

The game is a constant shooter, like a bullet hell, so the player firing continuously is the intended behavior. The charging happens when the player holds down the mouse button, and goes up to ~~(iirc) 2k~~ 8k projectiles, and releases all of them when the mouse button is released.

If there's an actual missing script (as in a script is showing as missing in the hierarchy) then that's probably my fault and I might have failed to commit something. Let me know if that's the case and feel free to reopen this issue!

Cheers

**Comment by dejaime** [comment]
Just to add a bit more information, looking at the Player prefab you'll find the following hierarchy:

![image](https://user-images.githubusercontent.com/2046959/148716919-5c9e6983-6525-41b4-90d7-9f86b3f03254.png)

The `CharacterController` game object does indeed have three scripts, `PlayerMovement`, `CameraMouseInput` and `TurretSpawner`. The turret spawner is responsible for spawning turrets (huh!), and it triggers with the right mouse button.

Notice though that it has no scripts related to the weapon. The weapon is actually nested in the hierarchy, and it holds its own `Weapon` script. The `staff` object is just for rendering, and has no logic attached.

Let me know if you have any further problems or questions!
